### ISSUE TITLE
你站点的 rss 订阅地址失效

### ISSUE THREAD

**Issue by a180285** [alanhg/alanhg.github.io#42]
很久以前订阅了你的博客，用的这个地址：
https://1991421.cn/atom.xml

今天在整理 rss 订阅源时，发现，这个地址失效了。而且也没有发现有新的 rss 订阅地址。希望可以更新一下

**Comment by alanhg** [comment]
> 很久以前订阅了你的博客，用的这个地址： https://1991421.cn/atom.xml
> 
> 今天在整理 rss 订阅源时，发现，这个地址失效了。而且也没有发现有新的 rss 订阅地址。希望可以更新一下

啊哈，好的，我处理下。
