### ISSUE TITLE
SEO-百度、谷歌收录

### ISSUE THREAD

**Issue by alanhg** [alanhg/alanhg.github.io#5]
如题

**Comment by heqiang421** [comment]
增加插件
``` 
 "hexo-generator-sitemap": "^1.1.2",
  "hexo-generator-baidu-sitemap": "^0.1.2",
```

**Comment by alanhg** [comment]
谷歌收录问题已经解决，百度收录不成功问题在于GitHub屏蔽了百度爬虫，考虑在GitHub之外部署一套，做成大陆IP访问走节点1，非大陆IP走节点2，分布部署

**Comment by alanhg** [comment]
百度爬虫抓取GitHub静态页403
![](http://or0g12e5e.bkt.clouddn.com/blog/2017-12-14-060809.png)

**Comment by alanhg** [comment]
个人博客，百度收录否，意义不大，暂时不考虑
