### ISSUE TITLE
解决项目源文件云端部署

### ISSUE THREAD

**Issue by alanhg** [alanhg/alanhg.github.io#7]
目前只是将生成的页面静态文件部署到github的个人仓库，主干下，但是一旦更换电脑，就很不方便

**Comment by heqiang421** [comment]
仓库增加`source`分支,存储项目源文件

**Comment by heqiang421** [comment]
# 目前发布文章操作步骤,`包含初始化电脑环境及开发运行环境`
1. git clone -b source 
2. npm i 
3. npm hexo-cli -g
4. hexo new 'postname'
5. git add .
6. git commit -m 'message'
7. git push
8. hexo g -d

# 改进空间

利用CI实现，提交源码，自动发布主干的静态页代码，将第八步去掉。

**Comment by alanhg** [comment]
利用travis-ci已经解决自动部署发布静态页
